import { KnowledgeFolder, KnowledgeItem } from './types';

export const mockFolders: KnowledgeFolder[] = [
  {
    id: 'folder-1',
    name: '제품 정보',
    parentId: null,
    createdAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'folder-2',
    name: '배송 정책',
    parentId: null,
    createdAt: Date.now() - 8 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 8 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'folder-3',
    name: '반품 및 환불',
    parentId: null,
    createdAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'folder-4',
    name: '스마트폰',
    parentId: 'folder-1',
    createdAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'folder-5',
    name: '노트북',
    parentId: 'folder-1',
    createdAt: Date.now() - 4 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 4 * 24 * 60 * 60 * 1000,
  },
];

export const mockKnowledgeItems: KnowledgeItem[] = [
  {
    id: 'item-1',
    title: '아이폰 15 Pro 주요 스펙',
    content: '아이폰 15 Pro는 6.1인치 Super Retina XDR 디스플레이를 탑재하고 있으며, A17 Pro 칩을 사용합니다. 카메라는 48MP 메인, 12MP 울트라 와이드, 12MP 망원 렌즈로 구성되어 있습니다. 배터리는 최대 23시간 비디오 재생이 가능합니다.',
    folderId: 'folder-4',
    isBookmarked: true,
    tags: ['아이폰', '스펙', '프로모션'],
    createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'item-2',
    title: '갤럭시 S24 Ultra 색상 옵션',
    content: '갤럭시 S24 Ultra는 티타늄 그레이, 티타늄 블랙, 티타늄 바이올렛, 티타늄 옐로우 4가지 색상으로 출시되었습니다. 온라인 한정으로 티타늄 그린, 티타늄 블루, 티타늄 오렌지 색상도 선택 가능합니다.',
    folderId: 'folder-4',
    isBookmarked: false,
    tags: ['갤럭시', '색상'],
    createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'item-3',
    title: '맥북 프로 M3 시리즈 비교',
    content: 'M3 맥북 프로는 14인치와 16인치 두 가지 사이즈로 출시됩니다. M3, M3 Pro, M3 Max 세 가지 칩 옵션이 있으며, 메모리는 최대 128GB까지 확장 가능합니다. 배터리는 14인치 기준 최대 17시간, 16인치는 최대 22시간 사용 가능합니다.',
    folderId: 'folder-5',
    isBookmarked: true,
    tags: ['맥북', '비교', 'M3'],
    createdAt: Date.now() - 4 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'item-4',
    title: 'LG 그램 경량 노트북 시리즈',
    content: 'LG 그램은 14인치(999g), 15인치(1.19kg), 16인치(1.28kg), 17인치(1.35kg)로 구성되어 있습니다. 모든 모델이 MIL-STD-810G 군용 규격을 통과하여 내구성이 우수하며, 80Wh 대용량 배터리로 최대 25.5시간 사용 가능합니다.',
    folderId: 'folder-5',
    isBookmarked: false,
    tags: ['LG', '그램', '경량'],
    createdAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'item-5',
    title: '일반 배송 처리 시간',
    content: '일반 배송은 주문 확인 후 1-2 영업일 내에 출고되며, 출고 후 2-3일 내에 배송됩니다. 제주도 및 도서산간 지역은 추가 1-2일이 소요될 수 있습니다. 주말 및 공휴일에는 배송이 지연될 수 있습니다.',
    folderId: 'folder-2',
    isBookmarked: true,
    tags: ['배송', '처리시간'],
    createdAt: Date.now() - 6 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 4 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'item-6',
    title: '빠른 배송 서비스 안내',
    content: '빠른 배송 서비스는 서울 및 수도권 지역에 한해 제공되며, 오전 11시 이전 주문 시 당일 배송이 가능합니다. 추가 배송비 3,000원이 발생하며, 일부 상품은 제외될 수 있습니다.',
    folderId: 'folder-2',
    isBookmarked: false,
    tags: ['빠른배송', '당일배송'],
    createdAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'item-7',
    title: '반품 가능 기간',
    content: '제품 수령 후 7일 이내에 반품 신청이 가능합니다. 단, 제품의 포장이 훼손되지 않은 상태여야 하며, 사용 흔적이 없어야 합니다. 전자제품의 경우 개봉 후 단순 변심에 의한 반품은 불가능할 수 있습니다.',
    folderId: 'folder-3',
    isBookmarked: true,
    tags: ['반품', '기간'],
    createdAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 6 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'item-8',
    title: '환불 처리 절차',
    content: '반품 승인 후 제품이 물류센터에 도착하면 1-2 영업일 내에 환불이 처리됩니다. 카드 결제의 경우 카드사 정책에 따라 환불 승인 후 3-5 영업일이 소요될 수 있습니다. 계좌 이체의 경우 즉시 환불 처리됩니다.',
    folderId: 'folder-3',
    isBookmarked: false,
    tags: ['환불', '처리'],
    createdAt: Date.now() - 8 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
  },
];
